name: ponto_ai
description: MVP de controle de ponto com reconhecimento facial (Flutter)
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+2
  http: ^1.2.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  geolocator: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
