name: Build Android APK

on:
  workflow_dispatch:
  push:
    paths:
      - 'lib/**'
      - 'pubspec.yaml'
      - '.github/workflows/build-apk.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_TOOL_OPTIONS: -Xmx2g

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      # Aceita licenças e garante SDK/build-tools (tenta ambos os caminhos do sdkmanager)
      - name: Android SDK & licenses
        shell: bash
        run: |
          set -e
          export ANDROID_SDK_ROOT="${ANDROID_SDK_ROOT:-$ANDROID_HOME}"
          SDKMGR="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager"
          if [ ! -f "$SDKMGR" ]; then
            SDKMGR="$ANDROID_SDK_ROOT/cmdline-tools/bin/sdkmanager"
          fi
          yes | "$SDKMGR" --licenses || true
          "$SDKMGR" "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      # Cria o esqueleto android/ se o repo tiver só lib/ + pubspec.yaml
      - name: Create Flutter skeleton if missing
        shell: bash
        run: |
          set -e
          if [ ! -d "android" ]; then
            mv lib lib_src
            mv pubspec.yaml pubspec_src.yaml
            flutter create . --platforms=android
            rm -rf lib
            mv lib_src lib
            mv pubspec_src.yaml pubspec.yaml
          fi

      - name: Flutter doctor (debug)
        run: flutter doctor -v

      - name: Flutter pub get
        run: flutter pub get

      - name: Build debug APK
        run: flutter build apk --debug

      - name: Build release APK
        run: flutter build apk --release

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: ponto-ai-apks
          path: |
            build/app/outputs/flutter-apk/app-debug.apk
            build/app/outputs/flutter-apk/app-release.apk
