name: Build Android APK

on:
  workflow_dispatch:
  push:
    paths:
      - 'lib/**'
      - 'pubspec.yaml'
      - '.github/workflows/build-apk.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JAVA_TOOL_OPTIONS: -Xmx2g

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Instala o Android SDK + componentes necessários e aceita licenças
      - name: Install Android SDK components
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          echo "y" | sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --licenses
          ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;34.0.0"

      # Se o repositório não tiver a pasta android/ (só lib/ e pubspec.yaml),
      # geramos o esqueleto e devolvemos seus arquivos.
      - name: Create Flutter skeleton if missing
        run: |
          set -e
          if [ ! -d "android" ]; then
            mv lib lib_src
            mv pubspec.yaml pubspec_src.yaml
            flutter create . --platforms=android
            rm -rf lib
            mv lib_src lib
            mv pubspec_src.yaml pubspec.yaml
          fi

      - name: Flutter pub get
        run: flutter pub get

      # Gera APK debug (assinado com debug-keystore, ideal para instalar no tablet)
      - name: Build debug APK
        run: flutter build apk --debug

      # (Opcional) também gerar release (ainda sem assinatura de release)
      - name: Build release APK
        run: flutter build apk --release

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: ponto-ai-apks
          path: |
            build/app/outputs/flutter-apk/app-debug.apk
            build/app/outputs/flutter-apk/app-release.apk
