name: Build Android APK

on:
  workflow_dispatch:
  push:
    paths:
      - 'lib/**'
      - 'pubspec.yaml'
      - '.github/workflows/build-apk.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Gera android/ caso o repo tenha só lib/ e pubspec.yaml
      - name: Create Flutter skeleton if missing
        run: |
          set -e
          if [ ! -d "android" ]; then
            mv lib lib_src
            mv pubspec.yaml pubspec_src.yaml
            flutter create . --platforms=android
            rm -rf lib
            mv lib_src lib
            mv pubspec_src.yaml pubspec.yaml
          fi

      - name: Flutter pub get
        run: flutter pub get

      - name: Build debug APK
        run: flutter build apk --debug

      - name: Build release APK
        run: flutter build apk --release

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: ponto-ai-apks
          path: |
            build/app/outputs/flutter-apk/app-debug.apk
            build/app/outputs/flutter-apk/app-release.apk
