name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main, principal ]
    paths:
      - '**/*.dart'
      - '**/pubspec.yaml'
      - '**/android/**'
      - '.github/workflows/build-apk.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Detect Flutter dir
        run: |
          if [ -f "mobile/pubspec.yaml" ]; then
            echo "FLUTTER_DIR=mobile" >> $GITHUB_ENV
          else
            echo "FLUTTER_DIR=." >> $GITHUB_ENV
          fi
          echo "Using dir: ${FLUTTER_DIR:-.}"

      - name: Ensure Android project
        run: |
          cd "$FLUTTER_DIR"
          if [ ! -d android ]; then
            flutter create . --platforms=android
          fi
          chmod +x android/gradlew

      - name: Flutter --version
        run: cd "$FLUTTER_DIR" && flutter --version

      - name: Flutter pub get
        run: cd "$FLUTTER_DIR" && flutter pub get

      - name: Build APK (debug)
        run: cd "$FLUTTER_DIR" && flutter build apk --debug

      - name: Build APK (release - unsigned)
        run: cd "$FLUTTER_DIR" && flutter build apk --release

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: ponto-ai-apks
          path: |
            ${{ env.FLUTTER_DIR }}/build/app/outputs/flutter-apk/app-debug.apk
            ${{ env.FLUTTER_DIR }}/build/app/outputs/flutter-apk/app-release.apk
