# .github/workflows/build-apk.yml
name: Construir APK Android

on:
  workflow_dispatch:
  push:
    branches: [ main, principal ]  # deixe os dois

jobs:
  build:
    runs-on: ubuntu-latest
    # Se seu projeto Flutter está na RAIZ, mude para "."
    defaults:
      run:
        working-directory: mobile

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17 (AGP 8+ exige JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - run: flutter --version
      - run: flutter pub get

      - name: Dar permissão ao gradlew
        run: chmod +x android/gradlew

      # APK debug (já assinado com keystore de debug) — ideal pra instalar no tablet
      - name: Build APK (debug)
        run: flutter build apk --debug

      # APK release (unsigned) — para publicar depois (precisa assinatura)
      - name: Build APK (release)
        run: flutter build apk --release

      - name: Upload APK debug
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: build/app/outputs/flutter-apk/app-debug.apk

      - name: Upload APK release (unsigned)
        uses: actions/upload-artifact@v4
        with:
          name: app-release-unsigned.apk
          path: build/app/outputs/flutter-apk/app-release.apk
